# Web Server Configuration
web_server:
  host: "0.0.0.0"
  port: 8000
  ssl_certfile: null  # Path to SSL certificate
  ssl_keyfile: null   # Path to SSL private key
  
  # CORS settings
  cors:
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["*"]

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: null
  db: 0
  
  # Queue settings
  queues:
    pending_orders: "orders:pending"
    matched_orders: "orders:matched"
    executed_orders: "orders:executed"
    failed_orders: "orders:failed"

# TradingView Webhook Settings
tradingview:
  webhook_secret: null  # Set via environment variable
  allowed_strategies: []  # Empty means all strategies allowed
  rate_limit:
    max_requests: 100
    time_window: 3600  # 1 hour

# Order Matching Settings
order_matching:
  loop_interval: 1.0  # seconds
  batch_size: 50
  max_execution_time: 30  # seconds
  
  # Risk limits
  max_order_value: 10000  # USD
  max_daily_orders: 1000
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/web_server.log" 